export default {
	PHRASE_CHANGED: 'PHRASE_CHANGED',
	PHRASE_COLLISION_LOADING: 'PHRASE_COLLISION_LOADING',
	PHRASE_VALIDATION_CHANGED: 'PHRASE_VALIDATION_CHANGED',
	SELECT_CAUSE: 'SELECT_CAUSE',
	SELECT_DESIGN: 'SELECT_DESIGN'
};